# Generated by Django 4.1.6 on 2023-07-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('cat_URL', models.CharField(max_length=100)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('blog_url', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='blog_img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BloggingApp.category')),
            ],
        ),
    ]
