# Generated by Django 4.1.6 on 2023-07-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
