# Generated by Django 4.1.6 on 2023-07-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0002_rename_blogs_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='content',
            new_name='description',
        ),
    ]
