# Generated by Django 4.1.6 on 2023-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BloggingApp', '0005_alter_blog_options_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
